# Generated by Django 2.2.6 on 2019-10-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landingReceiptNum', models.CharField(db_column='LandingReceiptNum', max_length=50)),
                ('landingDate', models.DateField(db_column='LandingDate')),
                ('fisherId', models.CharField(db_column='FisherID', max_length=50)),
                ('fisherName', models.CharField(db_column='FisherName', max_length=255)),
                ('fisherAbv', models.CharField(db_column='FisherAbv', max_length=4)),
                ('vesselID', models.IntegerField(db_column='VesselID')),
                ('fGVesselName', models.CharField(blank=True, db_column='FGVesselName', default=None, max_length=255, null=True)),
                ('vesselAbv', models.CharField(blank=True, db_column='VesselAbv', default=None, max_length=4, null=True)),
                ('statePermitNumber', models.CharField(blank=True, db_column='StatePermitNumber', default=None, max_length=20, null=True)),
                ('gFPermitNum', models.IntegerField(blank=True, db_column='GFPermitNum', default=None, null=True)),
                ('portID', models.IntegerField(db_column='PortID')),
                ('portName', models.CharField(db_column='PortName', max_length=255)),
                ('cDFWBlockID', models.IntegerField(db_column='CDFWBlockID')),
                ('blockName', models.CharField(db_column='BlockName', max_length=255)),
                ('businessID', models.IntegerField(db_column='BusinessID')),
                ('fishBusinessName', models.CharField(db_column='FishBusinessName', max_length=255)),
                ('businessAbv', models.CharField(db_column='BusinessAbv', max_length=4)),
                ('plantID', models.IntegerField(blank=True, db_column='PlantID', default=None, null=True)),
                ('primaryGearID', models.IntegerField(blank=True, db_column='PrimaryGearID', default=None, null=True)),
                ('primaryGearName', models.CharField(blank=True, db_column='PrimaryGearName', default=None, max_length=255, null=True)),
                ('speciesID', models.IntegerField(db_column='SpeciesID')),
                ('speciesName', models.CharField(db_column='SpeciesName', max_length=255)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', default=None, null=True)),
                ('pounds', models.IntegerField(db_column='Pounds')),
                ('unitPrice', models.FloatField(db_column='UnitPrice')),
                ('totalPrice', models.FloatField(db_column='TotalPrice')),
                ('gearID', models.IntegerField(db_column='GearID')),
                ('gearName', models.CharField(db_column='GearName', max_length=255)),
                ('depthName', models.CharField(blank=True, db_column='DepthName', default=None, max_length=255, null=True)),
                ('gradeName', models.CharField(blank=True, db_column='GradeName', default=None, max_length=255, null=True)),
                ('fishConditionID', models.IntegerField(db_column='FishConditionID')),
                ('fishConditionName', models.CharField(db_column='FishConditionName', max_length=255)),
                ('useID', models.IntegerField(db_column='UseID')),
                ('useName', models.CharField(db_column='UseName', max_length=255)),
            ],
        ),
    ]
