# Generated by Django 2.2.6 on 2019-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingrecord',
            name='fishConditionID',
            field=models.IntegerField(blank=True, db_column='FishConditionID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='landingrecord',
            name='fishConditionName',
            field=models.CharField(blank=True, db_column='FishConditionName', default=None, max_length=255, null=True),
        ),
    ]
