# Generated by Django 2.2.6 on 2019-10-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0004_auto_20191022_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingrecord',
            name='businessID',
            field=models.IntegerField(blank=True, db_column='BusinessID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='landingrecord',
            name='gearID',
            field=models.IntegerField(blank=True, db_column='GearID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='landingrecord',
            name='speciesID',
            field=models.IntegerField(blank=True, db_column='SpeciesID', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='landingrecord',
            name='vesselID',
            field=models.IntegerField(blank=True, db_column='VesselID', default=None, null=True),
        ),
    ]
