# Generated by Django 2.2.6 on 2019-10-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0005_auto_20191023_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingrecord',
            name='gFPermitNum',
            field=models.CharField(blank=True, db_column='GFPermitNum', default=None, max_length=50, null=True),
        ),
    ]
