# Generated by Django 2.2.6 on 2019-10-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0006_auto_20191023_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortGroupLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectShortCode', models.CharField(db_column='Project short code', max_length=255)),
                ('portName', models.CharField(db_column='Port name', max_length=100)),
                ('lat', models.FloatField(db_column='Lat')),
                ('lon', models.FloatField(db_column='Long')),
                ('portGroup', models.CharField(db_column='Port group', max_length=100)),
                ('californiaRegion', models.CharField(db_column='California Region', max_length=100)),
                ('portCode', models.IntegerField(db_column='Port code')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesGroupLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectShortCode', models.CharField(db_column='Project short code', max_length=255)),
                ('speciesCode', models.IntegerField(db_column='Species Code')),
                ('speciesName', models.CharField(db_column='Species Name', max_length=255)),
                ('commercialSpeciesGroup', models.CharField(db_column='Commercial Species Group', max_length=255)),
                ('gearCode', models.IntegerField(db_column='Gear Code')),
                ('gearDescription', models.CharField(db_column='Gear Description', max_length=255)),
                ('gearGroup', models.CharField(db_column='Gear Group', max_length=255)),
                ('commeciarlDataViewer', models.CharField(db_column='Commercial Data Viewer', max_length=4)),
                ('cPFVSpeciesGroup', models.CharField(db_column='CPFV Species Group', max_length=255)),
                ('cPFVDataViews', models.CharField(db_column='CPFV Data Viewer', max_length=4)),
            ],
        ),
    ]
