# Generated by Django 2.2.6 on 2019-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0007_portgrouplookup_speciesgrouplookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingrecord',
            name='portID',
            field=models.IntegerField(blank=True, db_column='PortID', default=None, null=True),
        ),
    ]
