# Generated by Django 2.2.6 on 2019-10-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0008_auto_20191028_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflationIndex',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('cpi', models.FloatField()),
                ('inflFactor', models.FloatField(blank=True, default=None, null=True)),
                ('yearCalculated', models.IntegerField(default=2018)),
            ],
        ),
    ]
