# Generated by Django 2.2.8 on 2020-01-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcdb', '0010_cpfvrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpfvrecord',
            name='hoursFished',
            field=models.FloatField(blank=True, db_column='HoursFished', default=None, null=True),
        ),
    ]
